package com.groupone.mobilestore.util;

import java.text.Normalizer;

public interface Constants {
    String BASE_URL = "https://nhom01nt118.azurewebsites.net/";

    //Constant Account
    String KEY_LOGIN = "KEY_LOGIN";
    String KEY_REGISTER = "KEY_REGISTER";
    String KEY_CHECK_REGISTER = "KEY_CHECK_REGISTER";
    String KEY_CHECK_EMAIL_EXIST = "KEY_CHECK_EMAIL_EXIST";
    String KEY_GET_BY_USERNAME = "KEY_GET_BY_USERNAME";
    String KEY_SEND_OTP = "KEY_SEND_OTP";
    String KEY_RESET_PASSWORD = "KEY_RESET_PASSWORD";
    String KEY_UPDATE_ACCOUNT = "KEY_UPDATE_ACCOUNT";
    String KEY_UPLOAD_IMAGE = "KEY_UPLOAD_IMAGE";
    String ACCESS_TOKEN = "ACCESS_TOKEN";
    String USERNAME = "USERNAME";

    //Constant Product
    String KEY_GET_TOP_SALE_PRODUCT = "KEY_GET_TOP_SALE_PRODUCT";


    //Constant Cart
    String KEY_ADD_SHOPPING_CART = "KEY_ADD_SHOPPING_CART";
    String KEY_GET_SHOPPING_CART_BY_ACCOUNT = "KEY_GET_SHOPPING_CART_BY_ACCOUNT";
    String KEY_DELETE_CART = "KEY_DELETE_CART";
    String KEY_UPDATE_QUANTITY = "KEY_UPDATE_QUANTITY";

    //Constant Shipment
    String KEY_ADD_SHIPMENT = "KEY_ADD_SHIPMENT";
    String KEY_GET_SHIPMENT_BY_ID = "KEY_GET_SHIPMENT_BY_ID";
    String KEY_GET_SHIPMENT_BY_ACCOUNT = "KEY_GET_SHIPMENT_BY_ACCOUNT";
    String KEY_UPDATE_SHIPMENT = "KEY_UPDATE_SHIPMENT";
    String KEY_DELETE_SHIPMENT = "KEY_DELETE_SHIPMENT";

    //Post
    String KEY_ALL_POST = "KEY_ALL_POST";

    //Favorite
    String KEY_ADD_FAVORITE = "KEY_ADD_FAVORITE";
    String KEY_DELETE_FAVORITE = "KEY_DELETE_FAVORITE";
    String KEY_DELETE_FAVORITE_BY_ACCOUNT = "KEY_DELETE_FAVORITE_BY_ACCOUNT";
    String KEY_GET_FAVORITE = "KEY_GET_FAVORITE";

    //Bank
    String KEY_ADD_BANK = "KEY_ADD_BANK";
    String KEY_DELETE_BANK = "KEY_DELETE_BANK";
    String KEY_GET_BANK = "KEY_GET_BANK";

    //Bill
    String KEY_ADD_BILL = "KEY_ADD_BILL";
    String KEY_GET_BILL = "KEY_GET_BILL";
    String KEY_UPDATE_BILL = "KEY_UPDATE_BILL";
    String KEY_CHANGE_STATUS_BILL = "KEY_CHANGE_STATUS_BILL";

}
