package com.groupone.mobilestore.util;

import java.text.Normalizer;

public interface Constants {
    String BASE_URL = "https://nhom01nt118.azurewebsites.net/";

    //Constant Account
    String KEY_LOGIN = "KEY_LOGIN";
    String KEY_REGISTER = "KEY_REGISTER";
    String KEY_CHECK_REGISTER = "KEY_CHECK_REGISTER";
    String KEY_CHECK_EMAIL_EXIST = "KEY_CHECK_EMAIL_EXIST";
    String KEY_GET_BY_USERNAME = "KEY_GET_BY_USERNAME";
    String KEY_SEND_OTP = "KEY_SEND_OTP";
    String KEY_RESET_PASSWORD = "KEY_RESET_PASSWORD";
    String KEY_UPDATE_ACCOUNT = "KEY_UPDATE_ACCOUNT";
    String KEY_UPLOAD_IMAGE = "KEY_UPLOAD_IMAGE";
    String ACCESS_TOKEN = "ACCESS_TOKEN";
    String USERNAME = "USERNAME";

    //Constant Product
    String KEY_GET_TOP_SALE_PRODUCT = "KEY_GET_TOP_SALE_PRODUCT";


    //Constant Cart
    String KEY_ADD_SHOPPING_CART = "KEY_ADD_SHOPPING_CART";
    String KEY_GET_SHOPPING_CART_BY_ACCOUNT = "KEY_GET_SHOPPING_CART_BY_ACCOUNT";
    String KEY_DELETE_CART = "KEY_DELETE_CART";
    String KEY_UPDATE_QUANTITY = "KEY_UPDATE_QUANTITY";

    //Constant Shipment
    String KEY_ADD_SHIPMENT = "KEY_ADD_SHIPMENT";
    String KEY_GET_SHIPMENT_BY_ID = "KEY_GET_SHIPMENT_BY_ID";
    String KEY_GET_SHIPMENT_BY_ACCOUNT = "KEY_GET_SHIPMENT_BY_ACCOUNT";
    String KEY_UPDATE_SHIPMENT = "KEY_UPDATE_SHIPMENT";
    String KEY_DELETE_SHIPMENT = "KEY_DELETE_SHIPMENT";


}
